# 开发环境会员认证系统配置
musk:
  auth:
    # 默认头像URL
    default-avatar-url: "https://dev.example.com/default-avatar.png"
    
    # 密码策略配置（开发环境相对宽松）
    password:
      min-length: 6                    # 最小长度
      require-uppercase: false         # 是否要求大写字母
      require-lowercase: false         # 是否要求小写字母
      require-digit: false             # 是否要求数字
      require-special-char: false      # 是否要求特殊字符

    # 验证码配置
    verification-code:
      # 邮箱验证码配置
      email:
        enabled: true                  # 是否启用邮箱验证码
        expire-seconds: 300            # 过期时间（秒）
        template-id: "email_login_template"  # 邮件模板ID
        frequency-limit-seconds: 60    # 发送频率限制（秒）
        dev-mode:
          enabled: true                # 是否启用开发模式
          fixed-code: "123456"         # 固定验证码
          skip-verification: false     # 是否跳过验证码验证
          allow-any-code: true         # 是否允许任意验证码（开发环境方便测试）

      # 短信验证码配置
      sms:
        enabled: true                  # 是否启用短信验证码
        expire-seconds: 300            # 过期时间（秒）
        provider: "aliyun"             # 短信服务提供商
        frequency-limit-seconds: 60    # 发送频率限制（秒）
        dev-mode:
          enabled: true                # 是否启用开发模式
          fixed-code: "123456"         # 固定验证码
          skip-verification: false     # 是否跳过验证码验证
          allow-any-code: true         # 是否允许任意验证码（开发环境方便测试）
      
      # 图形验证码配置
      captcha:
        enabled: true                  # 是否启用图形验证码
        expire-seconds: 300            # 过期时间（秒）
        dev-mode:
          enabled: true                # 是否启用开发模式
          fixed-code: "1234"          # 固定验证码
          skip-verification: false     # 是否跳过验证码验证
          allow-any-code: true         # 是否允许任意验证码（开发环境方便测试）

    # 第三方认证配置
    third-party:
      # 微信配置
      wechat:
        enabled: false                 # 开发环境暂时关闭
        app-id: "dev_app_id"
        app-secret: "dev_app_secret"

      # QQ配置
      qq:
        enabled: false                 # 开发环境暂时关闭
        app-id: "dev_qq_app_id"
        app-key: "dev_qq_app_key"

      # GitHub配置（开发环境测试用）
      github:
        enabled: true
        client-id: "dev_github_client_id"
        client-secret: "dev_github_client_secret"

# 日志配置（开发环境详细日志）
logging:
  level:
    org.example.musk.auth: DEBUG
    org.example.musk.auth.service.core.strategy: DEBUG
    org.example.musk.auth.service.core.chain: DEBUG
    org.example.musk.auth.service.core.code: DEBUG
    org.example.musk.auth.web.controller: DEBUG

# Spring配置
spring:
  profiles:
    active: dev
